name: Build and Deploy Product Branch

on:
  push:
    branches:
      - prod

env:
  AWS_REGION: ap-northeast-2  # 서울
  S3_BUCKET_NAME: sujanggo-website-prod-homepage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: deploy
        run:
          aws s3 sync ./ s3://${{ env.S3_BUCKET_NAME }}/ --delete
